baseURL = "https://xbetter.app/"
languageCode = "en-us"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "XBetter | Clean your X feed like a Mafioso."
paginate = 1
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

  [[module.mounts]]
    source = "assets"
    target = "assets"


[params]
  google_analytics_id = ""
  twitter_handle = "@donGiacobbe"
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  
  showIntroContentOnHomepage = true
  showPostsOnHomepage = false
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  
  sortPostsByDateOldestFirst = false
  
  addDot = true
  addFrame = true
  highlightColor = '#7B15FF'
  baseColor = "#000000"
  baseOffsetColor = "#eaeaea"
  headingColor = "#eaeaea"
  textColor = "#eaeaea"
  dotColor = "#7B15FF"
  
  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
  fontFamilyHeading = "Poppins"
  fontFamilyParagraph = "Helvetica"
  fontFamilyMonospace = "monospace"
  
  heroImage = true
  heroImagePath = "/images/hero.png"
  ctaLink = "https://forms.gle/NnREU6AnYfFhqsA89"
  ctaText = "BECOME THE X PIMP"
  

  footerImagePath = "/images/footer_image.png"
  footerLink = "https://venturecriminals.com"
  
  richPreviewImage = "/images/hero.png"
  richPreviewText = "Clean your X feed like a Mafioso."


# seo module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/basic-seo
# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Startups", "Venture", "Twitter", "X", "Warsaw", "Clean Twitter", "Clean X", "Indiehackers", "Solopreneurs", "X filters", "Twitter filters"]
description = "Clean your X feed like a Mafioso."
author = "Venture Criminals"
image = "images/hero.png"


# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

# [menu]
#   [[menu.main]]
#     identifier = 'home'
#     name = 'Home'
#     url = '/'
#     weight = 1
#   [[menu.main]]
#     name = "Blog"
#     identifier = "blog"
#     weight = 2
#     url = "/posts/"
#   [[menu.main]]
#     name = "About"
#     identifier = "about"
#     weight = 3
#     url = "/About/"
#   [[menu.main]]
#     name = "Tags"
#     identifier = "tags"
#     weight = 4
#     url = "/tags/"
