baseURL: "https://xbetter.app/"
theme: "up-business-theme"
languageCode: "en-us"

title: ""

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Up Business"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images: 
    - "images/Logo_with_text_no_margin.png"
    # - "images/hero-image.png"

  logo: "images/Logo_with_text_no_margin.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    # dribbble: "#"
    # instagram: "#"
    # facebook: "#"
    # twitter: "#"

  # location:
  #   - "3891 Ranchview Dr. Richardson, California 62639"
  #   - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "mafia@venturecriminals.com"

  copyright: "© 2024 Venture Criminals All Rights Reserved"

menus:
#   main:
#     - name: "Home"
#       url: "/#hero"
#       weight: 1

#     - name: "How we work"
#       url: "/#"
#       weight: 2

#     - name: "Our team"
#       url: "/#"
#       weight: 3

#     - name: "Pricing"
#       url: "/#"
#       weight: 4

#     - name: "Blog"
#       url: "/blog"
#       weight: 5

  buttons:
    - name: "Get on Chrome Store"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  # footer:
    # - name: "Home"
    #   url: "/#hero"
    #   weight: 1

    # - name: "How we work"
    #   url: "/#"
    #   weight: 2

    # - name: "Our team"
    #   url: "/#"
    #   weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

taxonomies:
  series: "series"
  tags: "tags"
